title: Figures of Consensus-based Rare Event Estimation
author: Konstantin Althaus

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

execute:
  execute_notebooks: force
  timeout: 30000

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: figures_paper.tex
